server:
  port: 8080
  servlet:
    context-path: /

spring:
  application:
    name: iot-project
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}

app:
  notification:
    email: ${NOTIFICATION_EMAIL:anhkhoabuivu@gmail.com}

# JWT Configuration
jwt:
  signerKey: ${JWT_SIGNER_KEY:cu+ODg482KxZvCd26KS9JRGbJZjtvGWrF+ZGlgqjIPTf5YImGQ9r/VDAjQUsTbgN}
  valid-duration: 3600 # seconds
  refresh-duration: 604800 # seconds